config/routes.rb
Rails.application.routes.draw do
  resources :drivers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "/cars" => "cars#index"
  get "/cars/new" => "cars#new"
  get "/cars/:id" => "cars#show"
  post "/cars/" => "cars#create"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
end

app/models/driver.rb
class Driver < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
    render "cars/index"
  end

  def new
    render "cars/new"
  end

  def show
    @car = Car.find(params[:id])
    render "cars/show"
  end

  def create
    car = Car.new(
      make: params[:make],
      model: params[:model],
      year: params[:year],
      price: params[:price]
    )
    car.save
    redirect_to "/cars/#{car.id}"
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: %i[ show edit update destroy ]

  # GET /drivers or /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1 or /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers or /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to driver_url(@driver), notice: "Driver was successfully created." }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1 or /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to driver_url(@driver), notice: "Driver was successfully updated." }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1 or /drivers/1.json
  def destroy
    @driver.destroy

    respond_to do |format|
      format.html { redirect_to drivers_url, notice: "Driver was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def driver_params
      params.require(:driver).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/cars/index.html.erb
<p>Hello there</p>

<% @cars.each do |car|%>
  <p><%= car.make %> <%= car.model %></p>
  <a href="/cars/<%= car.id %>">More Info</a>


<% end %>

app/views/cars/new.html.erb
<p>Create New Car</p>

<form action="/cars" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <p>Make: <input type="text" name ="make"></p>
  <p>Model: <input type="text" name ="model"></p>
  <p>Year: <input type="text" name ="year"></p>
  <p>Price: <input type="text" name ="price"></p>
  <p><input type="submit"></p>

</form>

app/views/cars/show.html.erb
<p>The Car</p>

<%= @car.id %>
<%= @car.make %>
<%= @car.model %>
<%= @car.year %>
<%= @car.price %>

<p><a href="/cars">Back to All Cars</a></p>

app/views/drivers/_driver.html.erb
<div id="<%= dom_id driver %>">
  <p>
    <strong>Name:</strong>
    <%= driver.name %>
  </p>

</div>

app/views/drivers/_form.html.erb
<%= form_with(model: driver) do |form| %>
  <% if driver.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
        <% driver.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing driver</h1>

<%= render "form", driver: @driver %>

<br>

<div>
  <%= link_to "Show this driver", @driver %> |
  <%= link_to "Back to drivers", drivers_path %>
</div>

app/views/drivers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Drivers</h1>

<div id="drivers">
  <% @drivers.each do |driver| %>
    <%= render driver %>
    <p>
      <%= link_to "Show this driver", driver %>
    </p>
  <% end %>
</div>

<%= link_to "New driver", new_driver_path %>

app/views/drivers/new.html.erb
<h1>New driver</h1>

<%= render "form", driver: @driver %>

<br>

<div>
  <%= link_to "Back to drivers", drivers_path %>
</div>

app/views/drivers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @driver %>

<div>
  <%= link_to "Edit this driver", edit_driver_path(@driver) %> |
  <%= link_to "Back to drivers", drivers_path %>

  <%= button_to "Destroy this driver", @driver, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <p><a href="/cars">Home</a></p>
    <title>CarApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>